//Character Dialogue as a string. Splice it every (20 words?)

//Divide lines of dialogue with ♡
//To change character expression, make sure to put the correct name before each line. this is REQUIRED!! Use "null" if a character has no expressions
//And repeat lines don't have the expression function -- so we also need a neutral named file (just character name) for that

const npcList = [
  { name: "Fluffy", dialogue: "null♡RAWR lol XD", repeatLine: "Raaaaawwwr."},
  { name: "Quincy", dialogue: "excited♡Oh, heya Aunt Jude! Are you here for the show?? <div class='flex-row'><button>Maybe later</button><button>No, Quincy</button></div>♡annoyed♡...of course you're not.<div class='flex-row'><button>Have you seen anything strange around here?</button></div>♡null♡Well, there's something going on with the forest to the west...♡concerned♡That place gives me the heebie-jeebies. I checked it out for the atmosphere for my show, but it's like, REAL scary, y'know? Always felt like I was being watched.♡null♡I'd stay away, myself... but if you're looking for strange, that's where I'd look.♡annoyed♡Anyway, if you change your mind about my show... I'll be here. Like always.", repeatLine: "<span>That forest is <i>bad news</i>, auntie. Be careful if you go that way. <i class='whisper'>I don't wanna get in trouble with mom...</i></span>"},
  { name: "Terracotta", dialogue: "neutral♡Hello there! I don't see strangers around here too often. What brings you to these parts?♡neutral♡<div class='flex-row'><button>Investigating strange rumours</button></div>♡concern♡Oh dear... I'm sorry, I can't say that I've seen anything strange around here lately.♡concern♡ I only really frequent this wildflower patch and the old church, myself.♡neutral♡I'm picking some flowers for the abandoned graves there right now, actually - I just hate to see them neglected.♡happy♡Please, if you have someone who needs a pick-me-up, take some yourself!", repeatLine: "I have the graves covered, but please feel free to take some flowers if you'd like! And good luck with your investigation!"},
  { name: "Crow", dialogue: "caw♡<span class='crow-scream'>CAW! cAw!</span>♡neutral♡Hello! Hello! Another brindle beast! ♡neutral♡You are alone! ♡null♡Alone, like it?", repeatLine: "..."},
  { name: "Acacia", dialogue: "null♡...♡null♡.....♡surprise♡..!♡embarassed♡Oh, good afternoon - I didn't see you there! I was bird watching. How can I help you?♡embarassed♡<div class='flex-row'><button>Have you seen anything strange around here?</button></div>♡embarassed♡Hmm... well...♡yap♡This is a green-winged teal, which is a rather rare around-<div class='flex-row'><button>Not with the birds</button></div>♡embarassed♡Oh... sorry. Let me think...♡ponder♡I HAVE noticed some odd footprints around here.♡yap♡There's the usual waterfowl and raccoons, and of course equid prints...♡ponder♡But also, a VERY large set of hoofprints. It could be from a horse?♡ponder♡But the stride seems a bit long for a horse, and the step too light... and, there aren't any around here that I've seen.♡embarassed♡I hope that's helpful in some way...", repeatLine: "I know you're busy, but if you have time later, I'd love to tell you more about the waterfowl here as well."},
  { name: "CainVatra", dialogue: "pant♡<i>huff... huff... huff... huff...</i>♡pant♡<div class='flex-row'><button>What happened?</button></div>♡caintalking♡<span>Theres - <i>huff</i> - a MONSTER in there!</span>♡vatratalking♡<span>A huge beast with glowing red eyes!</span>♡caintalking♡We went to explore the forest-♡vatratalking♡-and it came out of the brambles!♡pant♡We barely managed to get away...♡vatratalking♡<span>You're not planning to go IN there, are you?</span><div class='flex-row'><button>I think that's what I'm looking for</button></div>♡caintalking♡What???♡caintalking♡You're crazy!!♡vatratalking♡We can't stop you, but... it's your funeral.", repeatLine: "Nice knowing you..."},
  { name: "Gnash", dialogue: "null♡...♡null♡.....♡null♡Why... have you come here?<div class='flex-row'><button class='active' id='option-1'>Seeking something strange</button> <button id='option-3'>Seeking you</button></div>"},
  //Items Down Here
  { name: "Drawing", dialogue: "This drawing is yellowed and dirty, but seems to be of... an equid? Something seems off about it, though."},
  { name: "Daisy", dialogue: "A freshly picked daisy."},
  { name: "Hair", dialogue: "A clump of scraggly black hair, caught in the brambles. It smells like forest earth, mildew, and... iron? It's slightly greasy to the touch."},
  { name: "Bone", dialogue: "A broken femur bone, with deep grooves scratched into it from large gnawing teeth."},
  { name: "Feather", dialogue: "The primary feather of a crow. It has a slight iridescence to it."},
  { name: "Clover", dialogue: "A four leaf clover! Whether it's good luck, or a good snack for later, it's probably worth taking along."},
];